name       : yacreader
version    : 9.0.0
release    : 1
source     :
    - https://bitbucket.org/luisangelsm/yacreader/downloads/yacreader-9.0.0-src.tar.xz : 60bfefeb4cd0ce9e60cd2a6b0f976315e1781c2c1f8c5f43128ff9ebee760cc0
license    : GPL-3.0-or-later
component  : office.viewers
summary    : A comic reader for cross-platform reading and managing your digital comic collection.
description: |
    A comic reader for cross-platform reading and managing your digital comic collection.
builddeps  :
    - pkgconfig(glu) 
    - pkgconfig(libunarr)
    - pkgconfig(poppler-qt5) 
    - pkgconfig(Qt5Multimedia) 
    - pkgconfig(Qt5QuickControls2) 
    - pkgconfig(Qt5Script)
setup      : |
    %qmake PREFIX=$installdir/usr
build      : |
    %make
install    : |
    %make_install
