name       : yacreader
version    : 9.5.0
release    : 2
source     :
    - https://github.com/YACReader/yacreader/archive/9.5.0.tar.gz : 1104ffa78835b21a3cf611d42e52944ca413bf7feb38f7620fc07950e5f5ad40
license    : GPL-3.0-or-later
component  : office.viewers
summary    : A comic reader for cross-platform reading and managing your digital comic collection.
description: |
    A comic reader for cross-platform reading and managing your digital comic collection.
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(libunarr)
    - pkgconfig(poppler-qt5)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Script)
rundeps    :
    - qt5-quickcontrols
setup      : |
    %qmake PREFIX=$installdir/usr
build      : |
    %make
install    : |
    %make_install
