name       : yacreader
version    : 9.6.2
release    : 6
source     :
    - https://github.com/YACReader/yacreader/archive/9.6.2.tar.gz : e58cd10071180c759f53d74ac7049105b8608e63661bd1b68bcbd8fc8a534a80
license    : GPL-3.0-or-later
component  : office.viewers
summary    : Yet another comic reader
description: |
    A comic reader for cross-platform reading and managing your digital comic collection.
builddeps  :
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Script)
    - pkgconfig(libunarr)
    - pkgconfig(poppler-qt5)
rundeps    :
    - qt5-quickcontrols
setup      : |
    %patch -p1 < $pkgfiles/0001-removing-yacreader-library-server.patch
    %qmake PREFIX=$installdir/usr
build      : |
    %make
install    : |
    %make_install
