name       : yacreader
version    : 9.13.1
release    : 14
source     :
    - https://github.com/YACReader/yacreader/archive/refs/tags/9.13.1.tar.gz : 6863e9c7bbeb2c99fe09a29fab740cb0e15c7492de4fcd876e283b03041d3564
homepage   : https://www.yacreader.com/
license    : GPL-3.0-or-later
component  : office.viewers
summary    : Yet another comic reader
description: |
    A comic reader for cross-platform reading and managing your digital comic collection.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(libunarr)
    - pkgconfig(poppler-qt5)
rundeps    :
    - qt5-quickcontrols2
setup      : |
    %patch -p1 < $pkgfiles/0001-removing-yacreader-library-server.patch
    %qmake PREFIX=$installdir/usr
build      : |
    %make
install    : |
    %make_install
