name       : yacreader
version    : 9.8.2
release    : 10
source     :
    - https://github.com/YACReader/yacreader/archive/refs/tags/9.8.2.tar.gz : 44268a0c07a5ba3c25202064c088b1deba7cb048f6cbfcf33b3538f18225ae62
homepage   : https://www.yacreader.com/
license    : GPL-3.0-or-later
component  : office.viewers
summary    : Yet another comic reader
description: |
    A comic reader for cross-platform reading and managing your digital comic collection.
builddeps  :
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Svg)
    - pkgconfig(libunarr)
    - pkgconfig(poppler-qt5)
rundeps    :
    - qt5-quickcontrols
setup      : |
    %patch -p1 < $pkgfiles/0001-removing-yacreader-library-server.patch
    %qmake PREFIX=$installdir/usr
build      : |
    %make
install    : |
    %make_install
